### ISSUE TITLE
can still assign motors in a group to a cue (maybe gray them out instead of remove)

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#27]
When writing a cue, it is possible to select a grouped motor rather than needing to select the whole group.  this has been resolved in other places but just seems to have been missed in cue creation

**Comment by francotiveron** [comment]
This is by design:
When editing/creating a cue, there is no limitations, because the cue can be used in configurations different from the current.
However, in the Show page, cues that are inconsistent with the current configuration of the system are displayed with red border, so the user knows that the current system configuration is not compatible with that cue.

![image](https://user-images.githubusercontent.com/8280970/129437554-68cfb03d-d59f-4132-aae6-d846680851d1.png)

**Comment by francotiveron** [comment]
Please, confirm if the clarification above is ok (=> this issue is not to be actioned), or else...

**Comment by pkelm1** [comment]
I am not really against it just being disabled, but in my current testing, I have found that I have disabled cues and no real easy way to know why or get them functional again.  Normally, I delete then start over but this may not always be desirable. 

Is there a way to see what is bad in a cue?

**Comment by francotiveron** [comment]
![image](https://user-images.githubusercontent.com/8280970/132078716-a224c6e6-24d8-48c8-9b1c-1bd3f6ac6192.png)
